// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.11.2
// source: db_init.proto

package db_init

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	XcDB_InitNewXcDB_FullMethodName = "/api_db_init.XcDB/InitNewXcDB"
)

// XcDBClient is the client API for XcDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XcDBClient interface {
	InitNewXcDB(ctx context.Context, in *InitNewXcDBRequest, opts ...grpc.CallOption) (*InitNewXcDBResponse, error)
}

type xcDBClient struct {
	cc grpc.ClientConnInterface
}

func NewXcDBClient(cc grpc.ClientConnInterface) XcDBClient {
	return &xcDBClient{cc}
}

func (c *xcDBClient) InitNewXcDB(ctx context.Context, in *InitNewXcDBRequest, opts ...grpc.CallOption) (*InitNewXcDBResponse, error) {
	out := new(InitNewXcDBResponse)
	err := c.cc.Invoke(ctx, XcDB_InitNewXcDB_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XcDBServer is the server API for XcDB service.
// All implementations must embed UnimplementedXcDBServer
// for forward compatibility
type XcDBServer interface {
	InitNewXcDB(context.Context, *InitNewXcDBRequest) (*InitNewXcDBResponse, error)
	mustEmbedUnimplementedXcDBServer()
}

// UnimplementedXcDBServer must be embedded to have forward compatible implementations.
type UnimplementedXcDBServer struct {
}

func (UnimplementedXcDBServer) InitNewXcDB(context.Context, *InitNewXcDBRequest) (*InitNewXcDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitNewXcDB not implemented")
}
func (UnimplementedXcDBServer) mustEmbedUnimplementedXcDBServer() {}

// UnsafeXcDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XcDBServer will
// result in compilation errors.
type UnsafeXcDBServer interface {
	mustEmbedUnimplementedXcDBServer()
}

func RegisterXcDBServer(s grpc.ServiceRegistrar, srv XcDBServer) {
	s.RegisterService(&XcDB_ServiceDesc, srv)
}

func _XcDB_InitNewXcDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitNewXcDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XcDBServer).InitNewXcDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XcDB_InitNewXcDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XcDBServer).InitNewXcDB(ctx, req.(*InitNewXcDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XcDB_ServiceDesc is the grpc.ServiceDesc for XcDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XcDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api_db_init.XcDB",
	HandlerType: (*XcDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitNewXcDB",
			Handler:    _XcDB_InitNewXcDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db_init.proto",
}
