// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: db_init.proto

package db_init

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义请求消息
type InitNewXcDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigFilePath string `protobuf:"bytes,1,opt,name=configFilePath,proto3" json:"configFilePath,omitempty"`
	TestDataPath   string `protobuf:"bytes,2,opt,name=testDataPath,proto3" json:"testDataPath,omitempty"`
}

func (x *InitNewXcDBRequest) Reset() {
	*x = InitNewXcDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_init_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitNewXcDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNewXcDBRequest) ProtoMessage() {}

func (x *InitNewXcDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_init_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNewXcDBRequest.ProtoReflect.Descriptor instead.
func (*InitNewXcDBRequest) Descriptor() ([]byte, []int) {
	return file_db_init_proto_rawDescGZIP(), []int{0}
}

func (x *InitNewXcDBRequest) GetConfigFilePath() string {
	if x != nil {
		return x.ConfigFilePath
	}
	return ""
}

func (x *InitNewXcDBRequest) GetTestDataPath() string {
	if x != nil {
		return x.TestDataPath
	}
	return ""
}

// 定义响应消息
type InitNewXcDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
}

func (x *InitNewXcDBResponse) Reset() {
	*x = InitNewXcDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_init_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitNewXcDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitNewXcDBResponse) ProtoMessage() {}

func (x *InitNewXcDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_init_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitNewXcDBResponse.ProtoReflect.Descriptor instead.
func (*InitNewXcDBResponse) Descriptor() ([]byte, []int) {
	return file_db_init_proto_rawDescGZIP(), []int{1}
}

func (x *InitNewXcDBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitNewXcDBResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_db_init_proto protoreflect.FileDescriptor

var file_db_init_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x22, 0x60, 0x0a, 0x12,
	0x49, 0x6e, 0x69, 0x74, 0x4e, 0x65, 0x77, 0x58, 0x63, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65,
	0x50, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65,
	0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x74, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x61, 0x74, 0x68, 0x22, 0x53,
	0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x65, 0x77, 0x58, 0x63, 0x44, 0x42, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x58, 0x0a, 0x04, 0x58, 0x63, 0x44, 0x42, 0x12, 0x50, 0x0a, 0x0b, 0x49,
	0x6e, 0x69, 0x74, 0x4e, 0x65, 0x77, 0x58, 0x63, 0x44, 0x42, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x5f, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x65, 0x77,
	0x58, 0x63, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x65,
	0x77, 0x58, 0x63, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a,
	0x0b, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x62, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_init_proto_rawDescOnce sync.Once
	file_db_init_proto_rawDescData = file_db_init_proto_rawDesc
)

func file_db_init_proto_rawDescGZIP() []byte {
	file_db_init_proto_rawDescOnce.Do(func() {
		file_db_init_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_init_proto_rawDescData)
	})
	return file_db_init_proto_rawDescData
}

var file_db_init_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_db_init_proto_goTypes = []interface{}{
	(*InitNewXcDBRequest)(nil),  // 0: api_db_init.InitNewXcDBRequest
	(*InitNewXcDBResponse)(nil), // 1: api_db_init.InitNewXcDBResponse
}
var file_db_init_proto_depIdxs = []int32{
	0, // 0: api_db_init.XcDB.InitNewXcDB:input_type -> api_db_init.InitNewXcDBRequest
	1, // 1: api_db_init.XcDB.InitNewXcDB:output_type -> api_db_init.InitNewXcDBResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_init_proto_init() }
func file_db_init_proto_init() {
	if File_db_init_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_init_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitNewXcDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_init_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitNewXcDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_init_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_init_proto_goTypes,
		DependencyIndexes: file_db_init_proto_depIdxs,
		MessageInfos:      file_db_init_proto_msgTypes,
	}.Build()
	File_db_init_proto = out.File
	file_db_init_proto_rawDesc = nil
	file_db_init_proto_goTypes = nil
	file_db_init_proto_depIdxs = nil
}
