// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.11.2
// source: db_set.proto

package db_set

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SAddRequest 表示 SAdd RPC 的请求消息。
type SAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members [][]byte `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Ttl     []uint64 `protobuf:"varint,3,rep,packed,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{0}
}

func (x *SAddRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SAddRequest) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *SAddRequest) GetTtl() []uint64 {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// SAddResponse 表示 SAdd RPC 的响应消息。
type SAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SAddResponse) Reset() {
	*x = SAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddResponse) ProtoMessage() {}

func (x *SAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddResponse.ProtoReflect.Descriptor instead.
func (*SAddResponse) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{1}
}

func (x *SAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SRemRequest 表示 SRem RPC 的请求消息。
type SRemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members [][]byte `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SRemRequest) Reset() {
	*x = SRemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRequest) ProtoMessage() {}

func (x *SRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRequest.ProtoReflect.Descriptor instead.
func (*SRemRequest) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{2}
}

func (x *SRemRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SRemRequest) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

// SRemResponse 表示 SRem RPC 的响应消息。
type SRemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SRemResponse) Reset() {
	*x = SRemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemResponse) ProtoMessage() {}

func (x *SRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemResponse.ProtoReflect.Descriptor instead.
func (*SRemResponse) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{3}
}

func (x *SRemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SMembersRequest 表示 SMembers RPC 的请求消息。
type SMembersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{4}
}

func (x *SMembersRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// SMembersResponse 表示 SMembers RPC 的响应消息。
type SMembersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members [][]byte `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{5}
}

func (x *SMembersResponse) GetMembers() [][]byte {
	if x != nil {
		return x.Members
	}
	return nil
}

// SIsMemberRequest 表示 SIsMember RPC 的请求消息。
type SIsMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member []byte `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *SIsMemberRequest) Reset() {
	*x = SIsMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberRequest) ProtoMessage() {}

func (x *SIsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberRequest.ProtoReflect.Descriptor instead.
func (*SIsMemberRequest) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{6}
}

func (x *SIsMemberRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SIsMemberRequest) GetMember() []byte {
	if x != nil {
		return x.Member
	}
	return nil
}

// SIsMemberResponse 表示 SIsMember RPC 的响应消息。
type SIsMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *SIsMemberResponse) Reset() {
	*x = SIsMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SIsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberResponse) ProtoMessage() {}

func (x *SIsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberResponse.ProtoReflect.Descriptor instead.
func (*SIsMemberResponse) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{7}
}

func (x *SIsMemberResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// SCardRequest 表示 SCard RPC 的请求消息。
type SCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *SCardRequest) Reset() {
	*x = SCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardRequest) ProtoMessage() {}

func (x *SCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardRequest.ProtoReflect.Descriptor instead.
func (*SCardRequest) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{8}
}

func (x *SCardRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

// SCardResponse 表示 SCard RPC 的响应消息。
type SCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *SCardResponse) Reset() {
	*x = SCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_set_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCardResponse) ProtoMessage() {}

func (x *SCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_set_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCardResponse.ProtoReflect.Descriptor instead.
func (*SCardResponse) Descriptor() ([]byte, []int) {
	return file_db_set_proto_rawDescGZIP(), []int{9}
}

func (x *SCardResponse) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

var File_db_set_proto protoreflect.FileDescriptor

var file_db_set_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x22, 0x4b, 0x0a, 0x0b, 0x53, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x28, 0x0a, 0x0c, 0x53, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x39, 0x0a, 0x0b, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x28, 0x0a, 0x0c,
	0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2c, 0x0a, 0x10, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x3c, 0x0a, 0x10, 0x53, 0x49, 0x73,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2b, 0x0a, 0x11, 0x53, 0x49, 0x73, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78,
	0x69, 0x73, 0x74, 0x73, 0x22, 0x20, 0x0a, 0x0c, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x32,
	0xd2, 0x02, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12,
	0x39, 0x0a, 0x04, 0x53, 0x41, 0x64, 0x64, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62,
	0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x53, 0x52,
	0x65, 0x6d, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e,
	0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70,
	0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x52, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x53, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09,
	0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62,
	0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x73, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x05, 0x53, 0x43, 0x61, 0x72, 0x64, 0x12,
	0x18, 0x2e, 0x61, 0x70, 0x69, 0x5f, 0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x5f,
	0x64, 0x62, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x62, 0x5f, 0x73,
	0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_set_proto_rawDescOnce sync.Once
	file_db_set_proto_rawDescData = file_db_set_proto_rawDesc
)

func file_db_set_proto_rawDescGZIP() []byte {
	file_db_set_proto_rawDescOnce.Do(func() {
		file_db_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_set_proto_rawDescData)
	})
	return file_db_set_proto_rawDescData
}

var file_db_set_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_db_set_proto_goTypes = []interface{}{
	(*SAddRequest)(nil),       // 0: api_db_set.SAddRequest
	(*SAddResponse)(nil),      // 1: api_db_set.SAddResponse
	(*SRemRequest)(nil),       // 2: api_db_set.SRemRequest
	(*SRemResponse)(nil),      // 3: api_db_set.SRemResponse
	(*SMembersRequest)(nil),   // 4: api_db_set.SMembersRequest
	(*SMembersResponse)(nil),  // 5: api_db_set.SMembersResponse
	(*SIsMemberRequest)(nil),  // 6: api_db_set.SIsMemberRequest
	(*SIsMemberResponse)(nil), // 7: api_db_set.SIsMemberResponse
	(*SCardRequest)(nil),      // 8: api_db_set.SCardRequest
	(*SCardResponse)(nil),     // 9: api_db_set.SCardResponse
}
var file_db_set_proto_depIdxs = []int32{
	0, // 0: api_db_set.SetDatabase.SAdd:input_type -> api_db_set.SAddRequest
	2, // 1: api_db_set.SetDatabase.SRem:input_type -> api_db_set.SRemRequest
	4, // 2: api_db_set.SetDatabase.SMembers:input_type -> api_db_set.SMembersRequest
	6, // 3: api_db_set.SetDatabase.SIsMember:input_type -> api_db_set.SIsMemberRequest
	8, // 4: api_db_set.SetDatabase.SCard:input_type -> api_db_set.SCardRequest
	1, // 5: api_db_set.SetDatabase.SAdd:output_type -> api_db_set.SAddResponse
	3, // 6: api_db_set.SetDatabase.SRem:output_type -> api_db_set.SRemResponse
	5, // 7: api_db_set.SetDatabase.SMembers:output_type -> api_db_set.SMembersResponse
	7, // 8: api_db_set.SetDatabase.SIsMember:output_type -> api_db_set.SIsMemberResponse
	9, // 9: api_db_set.SetDatabase.SCard:output_type -> api_db_set.SCardResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_set_proto_init() }
func file_db_set_proto_init() {
	if File_db_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SRemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMembersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SIsMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_set_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_set_proto_goTypes,
		DependencyIndexes: file_db_set_proto_depIdxs,
		MessageInfos:      file_db_set_proto_msgTypes,
	}.Build()
	File_db_set_proto = out.File
	file_db_set_proto_rawDesc = nil
	file_db_set_proto_goTypes = nil
	file_db_set_proto_depIdxs = nil
}
